In [1]:
import pandas as pd

In [2]:
pred = pd.read_csv("output/pred.csv")
pred.head()

         qid answer
0  test_0001      A
1  test_0002      B
2  test_0003      B
3  test_0004      A
4  test_0005      A

In [3]:
result = pd.read_csv("results/test_1780332041.csv")
result.head()

,test_0001,test_0002,test_0003,test_0004,test_0005,test_0006,test_0007,test_0008,test_0009,test_0010,...,test_0454,test_0455,test_0456,test_0457,test_0458,test_0459,test_0460,test_0461,test_0462,test_0463
0,D,B,B,C,C,A,B,B,C,B,...,B,B,C,D,D,C,A,B,C,B
1,RAG,math,RAG,RAG,RAG,math,multi_domain,math,math,multi_domain,...,multi_domain,multi_domain,multi_domain,math,math,RAG,RAG,multi_domain,multi_domain,multi_domain

In [4]:
submission = pd.DataFrame({
    "qid": result.columns,
    "answer": result.iloc[0].values,
    "domain": result.iloc[1].values
})

submission.head()

         qid answer domain
0  test_0001      D    RAG
1  test_0002      B   math
2  test_0003      B    RAG
3  test_0004      C    RAG
4  test_0005      C    RAG

In [5]:
merge_ = pd.merge(pred, submission, on="qid", how="left")
merge_.head()

         qid answer_x answer_y domain
0  test_0001        A        D    RAG
1  test_0002        B        B   math
2  test_0003        B        B    RAG
3  test_0004        A        C    RAG
4  test_0005        A        C    RAG

In [6]:
a = merge_['answer_x'] == merge_['answer_y']
a.value_counts()

True     303
False    160
Name: count, dtype: int64

In [8]:
diff = merge_[merge_['answer_x'] != merge_['answer_y']]

stats_ = diff[['qid', 'domain']]

In [10]:
stats_['domain'].value_counts()

domain
multi_domain      60
math              54
RAG               24
should_correct    19
ignore_answer      3
Name: count, dtype: int64

In [11]:
correct = merge_[merge_['answer_x'] == merge_['answer_y']]
correct['domain'].value_counts()

domain
multi_domain      122
RAG                77
math               66
should_correct     31
ignore_answer       7
Name: count, dtype: int64